force-app/main/default/objects/AuditAccount__c/AuditAccount__c.object-meta.xml
<CustomObject>
    <label>Audit Account</label>
    <nameField>
        <label>Audit Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditAccount__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AuditContact__c/AuditContact__c.object-meta.xml
<CustomObject>
    <label>Audit Contact</label>
    <nameField>
        <label>Audit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditContact__c/fields/ChangeDate__c.field-meta.xml
<CustomField>
    <fullName>ChangeDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>ChangeDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AuditContact__c/fields/ConcernedObject__c.field-meta.xml
<CustomField>
    <fullName>ConcernedObject__c</fullName>
    <label>ConcernedObject</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuditContract__c/AuditContract__c.object-meta.xml
<CustomObject>
    <label>Audit Contract</label>
    <nameField>
        <label>Con Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditContracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditContract__c/fields/ConcernedObject__c.field-meta.xml
<CustomField>
    <fullName>ConcernedObject__c</fullName>
    <label>ConcernedObject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuditLead__c/AuditLead__c.object-meta.xml
<CustomObject>
    <label>Audit Lead</label>
    <nameField>
        <label>AuditLead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditLeads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditLead__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AuditOpportunity__c/AuditOpportunity__c.object-meta.xml
<CustomObject>
    <label>Audit Opportunity</label>
    <nameField>
        <label>AuditOpportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuditOpportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditProduct__c/AuditProduct__c.object-meta.xml
<CustomObject>
    <label>Audit Product</label>
    <nameField>
        <label>Audit Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuditProduct__c/fields/ChangeDate__c.field-meta.xml
<CustomField>
    <fullName>ChangeDate__c</fullName>
    <label>ChangeDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AuditPdf.cls
public with sharing class AuditPdf {
    public List<AuditContact__c> Records {get; set;}
    public List<AuditContract__c> contracts {get; set;}
    public List<AuditLead__c> Leads {get; set;}
    public List<AuditProduct__c> Products {get; set;}
    public List<AuditOpportunity__c> Opportunities {get; set;}
    public List<AuditAccount__c> Accounts {get; set;}

    public AuditPdf() {
        this.Records =  [
            SELECT User_ID__c, Action__c, 
            ChangeDate__c, ConcernedObject__c
            FROM AuditContact__c  ORDER BY ChangeDate__c ];
        this.contracts =  [
                SELECT User_ID__c, Action__c, 
                ChangeDate__c, ConcernedObject__c
                FROM AuditContract__c  ORDER BY ChangeDate__c ]; 
        this.Leads =  [
                SELECT User_ID__c, Action__c, 
                ChangeDate__c, ConcernedObject__c
                FROM AuditLead__c  ORDER BY ChangeDate__c ]; 
        this.Products =  [
                SELECT User_ID__c, Action__c, 
                ChangeDate__c, ConcernedObject__c
                FROM AuditProduct__c  ORDER BY ChangeDate__c ]; 
        this.Opportunities =  [
                SELECT User_ID__c, Action__c, 
                ChangeDate__c, ConcernedObject__c
                FROM AuditOpportunity__c  ORDER BY ChangeDate__c ]; 
        this.Accounts =  [
                SELECT User_ID__c, Action__c, 
                ChangeDate__c, ConcernedObject__c
                FROM AuditAccount__c  ORDER BY ChangeDate__c ];                     
    }
    @Future(callout=true)
    @AuraEnabled
    public static void sendReport() {
 
        string [] toaddress= New string[]{'imenghouil21@gmail.com'};
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setToAddresses(toaddress);
        message.setSubject('Audit de la semaine ');
        message.setsaveasactivity(false);

        message.setHtmlBody('Votre audit de la semaine des donées Salesforce');
        
     
        PageReference pdf = Page.AuditPdf;
            
        Blob reportPdf;
        try {
            reportPdf = pdf.getContentAsPDF();
        }
        catch (Exception e) {
            reportPdf = Blob.valueOf(e.getMessage());
        }
        
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setContentType('application/pdf');
        attachment.setFileName('Audit : '+system.today().format());
        attachment.setInline(false);
        attachment.setBody(reportPdf);
        message.setFileAttachments(new Messaging.EmailFileAttachment[]{ attachment });
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ message });
        
    }
}